name: Secrets workflow

on:
  pull_request:
    branches: [ "main" ]  

jobs:
  secrets:
    name : Secrets Job
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variables
        run: echo "Te pongo texto ${{ secrets.SECRET_API_KEY }} "