name: Secrets workflow

on:
  pull_request:
    branches: [ "main" ]  

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.csproj"

jobs:
  secrets:
    name : Secrets Job
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variables
        run: echo "$API_CSPROJ_PATH"


